AWSTemplateFormatVersion: "2010-09-09"
Description: ibm vpc for project
Resources:
  ibmVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
      - Key: Name
        Value: ibm-vpc

  ibmInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: ibm-igw

  ibmAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: ibmVPC
      InternetGatewayId:
        Ref: ibmInternetGateway

  ibmwebSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: ibmVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-east-2a"
      MapPublicIpOnLaunch: 'true'
      Tags:
      - Key: Name
        Value: ibm-web-subnet

  ibmdbSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: ibmVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "us-east-2b"
      MapPublicIpOnLaunch: 'false'
      Tags:
      - Key: Name
        Value: ibm-db-subnet

  ibmwebRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: ibmVPC
      Tags:
      - Key: Name
        Value: ibm-web-route

  ibmdbRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: ibmVPC
      Tags:
      - Key: Name
        Value: ibm-db-route

  ibmigwRoute:
    Type: AWS::EC2::Route
    DependsOn: ibmAttachGateway
    Properties:
       RouteTableId:
         Ref: ibmwebRouteTable
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId:
         Ref: ibmInternetGateway

  ibmwebSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: ibmwebSubnet
      RouteTableId:
        Ref: ibmwebRouteTable

  ibmdbSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: ibmdbSubnet
      RouteTableId:
        Ref: ibmdbRouteTable

  ibmwebNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
        VpcId:
          Ref: ibmVPC
        Tags:
        - Key: Name
          Value: ibm-web-nacl        
  ibmwebInboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId:
         Ref: ibmwebNetworkAcl
       RuleNumber: 100
       Protocol: 6
       RuleAction: allow
       CidrBlock: 0.0.0.0/0
       PortRange:
         From: 0
         To: 65535
  ibmwebOutboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId:
         Ref: ibmwebNetworkAcl
       RuleNumber: 100
       Protocol: -1
       Egress: true
       RuleAction: allow
       CidrBlock: 0.0.0.0/0

  ibmwebSubnetNetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId:
        Ref: ibmwebSubnet
      NetworkAclId:
        Ref: ibmwebNetworkAcl


  ibmdbNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
        VpcId:
          Ref: ibmVPC
        Tags:
        - Key: Name
          Value: ibm-db-nacl        
  ibmdbInboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId:
         Ref: ibmdbNetworkAcl
       RuleNumber: 100
       Protocol: 6
       RuleAction: allow
       CidrBlock: 0.0.0.0/0
       PortRange:
         From: 0
         To: 65535
  ibmdbOutboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId:
         Ref: ibmdbNetworkAcl
       RuleNumber: 100
       Protocol: -1
       Egress: true
       RuleAction: allow
       CidrBlock: 0.0.0.0/0

  ibmdbSubnetNetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId:
        Ref: ibmdbSubnet
      NetworkAclId:
        Ref: ibmdbNetworkAcl

  ibmwebInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ibm traffic
      VpcId: !Ref ibmVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: ibm-web-sg

  ibmdbInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ibm traffic
      VpcId: !Ref ibmVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/16
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: ibm-db-sg
